name: Generate PAC

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: update
        run: |
          bash -x doall.sh
          mkdir -p output && cp result/proxy-host-*.pac output
          echo DATE=$(date --utc "+%Y-%m-%d %H:%M %Z") >> $GITHUB_ENV

      - name: Push to GH Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: output
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          commit-message: 'Update PAC files ${{ env.DATE }}'
          single-commit: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        continue-on-error: true
